import express from 'express';
import cors from 'cors';
import cookieParser from 'cookie-parser';
import morgan from 'morgan';
import authRoutes from './routes/authRoutes.js';
import profileRoutes from './routes/profileRoutes.js';
import schemeRoutes from './routes/schemeRoutes.js';
import recommendationRoutes from './routes/recommendationRoutes.js';
import bookmarkRoutes from './routes/bookmarkRoutes.js';
import notificationRoutes from './routes/notificationRoutes.js';
import aiRoutes from './routes/aiRoutes.js';

const app=express();
app.use(cors({origin:process.env.CLIENT_URL || 'http://localhost:5173',credentials:true}));
app.use(express.json({limit:'1mb'})); app.use(cookieParser()); app.use(morgan('dev'));
app.get('/api/health',(req,res)=>res.json({ok:true,service:'SchemeSathi API'}));
app.use('/api/auth',authRoutes); app.use('/api/profile',profileRoutes); app.use('/api/schemes',schemeRoutes); app.use('/api/recommendations',recommendationRoutes); app.use('/api/bookmarks',bookmarkRoutes); app.use('/api/notifications',notificationRoutes); app.use('/api/assistant',aiRoutes);
app.use((req,res)=>res.status(404).json({message:'Route not found'}));
app.use((err,req,res,next)=>{ console.error(err); res.status(err.name==='ValidationError'?400:500).json({message:err.message || 'Server error'}); });
export default app;
